package org.spring.barman.records;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class RecordEquality {

    private static final Logger log = LoggerFactory.getLogger(RecordEquality.class);

    /**
     *
     * Records are shallowly immutable
     * It contains getter, toString, hashcode, autogenerated constructor by default
     */
    record Person(String fName, String lName) {}

    static void main() {
        var person1 = new Person("John", "Doe");
        var person2 = new Person("John", "Doe");
        var person3 = new Person("John3", "Doe3");

        log.info("person1 == person2: {}", person1 == person2);
        log.info("toString:{}", person1);//default toString()
        log.info("hashCode for person1:{}", person1.hashCode());
        log.info("hashCode for person2:{}", person2.hashCode());
        log.info("equals: {}", person1.equals(person2)); //true as will check the content
    }
}
